name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - run: mvn -f employee-service/pom.xml clean verify

      - name: JIB Imaged
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - run: mvn -f employee-service/pom.xml -Dmaven.test.skip=true package jib:build -Djib.to.auth.username=$DOCKER_USER -Djib.to.auth.password=$DOCKER_TOKEN

